### ISSUE TITLE
Inputs and includes ? (from latex to another format)

### ISSUE THREAD

**Issue by spartiot** [dsanson/Pandoc-Droplets-and-Services#3]
Hi,
When I use pandoc through shell everything works fine.
But when I try to use your droplets and services, the converted file (output file) does not display included .tex files (by \include{} or \input{} command). Do you know why and is it possible to change that ?

I tried to convert .tex file into .docx

Thank you :)

**Comment by dsanson** [comment]
Not sure, but my first guess is that it is a path problem. Does it work if you specify your include using an absolute path?

**Comment by spartiot** [comment]
Ok, thank you. It must be this.
I can't use an absolute path so I will run pandoc through the shell.

2015-04-16 17:16 GMT+02:00 David Sanson <notifications@github.com>:

**Comment by dsanson** [comment]
Should be resolved by  commit 7405501c4. Reopen if not.
