### ISSUE TITLE
PDF service no longer working

### ISSUE THREAD

**Issue by mendelkranz** [dsanson/Pandoc-Droplets-and-Services#4]
Hi, thanks for an extremely useful tool. For some reason the PDF service stopped working. Did something change in El Capitan? Do you know of any reason why this would happen?

**Comment by dsanson** [comment]
This is probably because the path to TeX has changed in El Capitan. I just pushed commit f22fd4b that updates the path to include `/Library/TeX/texbin`. Let me know if that fixes the problem.

**Comment by mendelkranz** [comment]
That did it, thanks a lot!

Mendel Kranz
University of Chicago
MA Student, Divinity School

On November 30, 2015 at 5:08:53 PM, David Sanson (notifications@github.com) wrote:

This is probably because the path to TeX has changed in El Capitan. I just pushed commit f22fd4b that updates the path to include /Library/TeX/texbin. Let me know if that fixes the problem.
